---
tree:
- [TORSO_LINK,HEAD_LINK]
- [TORSO_LINK,L_ARM_LINK,L_FOREARM_LINK,L_HAND_LINK]
- [TORSO_LINK,R_ARM_LINK,R_FOREARM_LINK,R_HAND_LINK]

links:
- name: TORSO_LINK
  child: ["HEAD_R_LINK","L_SHOULDER_R_LINK","R_SHOULDER_R_LINK"]
  dimension: [0.1,0.3,0.4]
- name: HEAD_LINK
  child: []
  dimension: [0.05]
- name: L_ARM_LINK
  child: [L_FOREARM_LINK]
  dimension: [0.2,0.025]
- name: L_FOREARM_LINK
  child: [L_WRIST_R_LINK]
  dimension: [0.25,0.025]
- name: L_HAND_LINK
  child: []
  dimension: [0.12,0.025]
- name: R_ARM_LINK
  child: [R_FOREARM_LINK]
  dimension: [0.2,0.025]
- name: R_FOREARM_LINK
  child: [R_WRIST_R_LINK]
  dimension: [0.25,0.025]
- name: R_HAND_LINK
  child: []
  dimension: [0.12,0.025]